# 1. Escolher a base
FROM node:24-alpine

# 2. Definir o diretório de trabalho dentro do container
WORKDIR /app

# 3. Copiar os arquivos do projeto para dentro do container
COPY package.json ./

# 4. Instalar as dependências
RUN npm install

# 5. copiar o resto do código
COPY . .

# 6. Expor a porta (precisa ser 80)
EXPOSE 80

# 7. Definir o comando padrão para rodar o container
CMD ["node", "server.js"]