name: Destroy All EC2 Instances

on:
  workflow_dispatch:

jobs:
  destroy:
    if: ${{ github.actor == 'EnricoSantarelli' }}
    runs-on: ubuntu-latest

    steps:
      - name: Instalar ou atualizar AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configurar credenciais AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Configurando credenciais AWS..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Listar e destruir todas as inst창ncias EC2
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].InstanceId' \
            --output text)

          if [ -z "$INSTANCE_IDS" ]; then
            echo "Nenhuma inst창ncia encontrada."
          else
            echo "Encerrando as inst창ncias: $INSTANCE_IDS"
            aws ec2 terminate-instances --instance-ids $INSTANCE_IDS
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_IDS
            echo "Todas as inst창ncias foram encerradas com sucesso."
          fi
